Kollaborator/Kollaborator.web/Models/GroupViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Kollaborator.web.Models
{
    public class GroupViewModel
    {
        public GroupModel group;
        public List<FileModel> files;
        public List<ApplicationUser> users;
        public List<ChatModel> messages;
        public string UserName=null;
        public GroupViewModel(int groupID)
        {
            using (var ctx = new ApplicationDbContext())
            {
                 group = ctx.Groups.Where(p => p.groupID == groupID).FirstOrDefault();
                 users = ctx.userGroups.Where(p => p.groupID == groupID).Select(p => p.user).ToList();
                 files = ctx.file.Where(p => p.groupId == groupID).ToList();
                 messages = ctx.chat.Where(p => p.groupID == groupID).ToList();
            }
        }
    }
}

Kollaborator/Kollaborator.web/Controllers/GroupController.cs
using Kollaborator.web.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using Microsoft.AspNet.SignalR;
using System.Web.Routing;
using Newtonsoft.Json;
using System.Text.RegularExpressions;

namespace Kollaborator.web.Controllers
{
    public class GroupController : Controller
    {
        private const int MESSAGE_NUMBER = 25;
        // GET: Group
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                using (var ctx = new ApplicationDbContext())
                {
                    var userName = WebSecurity.CurrentUserName;

                    var groupList = ctx.Users
                        .Where(p => p.UserName == userName)
                        .SelectMany(p => p.userGroups.Select(ug => ug.group)).
                        ToList();


                    return View(groupList);
                }
            }
            else
            {
                return View();
            }
        }
        public PartialViewResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(GroupModel group, IEnumerable<ApplicationUser> users)
        {
             using (var ctx = new ApplicationDbContext())
            {
                var user = ctx.Users.Where(p => p.UserName == WebSecurity.CurrentUserName).FirstOrDefault();
                group.creator = user.UserName;
                var usergroup = new UserGroup
                {
                    user = user,
                    group = group
                };
                ctx.Groups.Add(group);
                ctx.userGroups.Add(usergroup);

                if (!(users == null))
                {
                    foreach (var person in users)
                    {
                        var sth = ctx.Users.FirstOrDefault(p => p.UserName.Equals(person.UserName));
                        if (sth != null)
                        {
                            usergroup = new UserGroup
                            {
                                UserID = sth.Id,

                                groupID = group.groupID,

                            };
                            ctx.userGroups.Add(usergroup);
                        }


                    }
                }
                try {
                    // Your code...
                    // Could also be before try if you know the exception occurs in SaveChanges

                    ctx.SaveChanges();
                }
                catch (DbEntityValidationException e){
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }
                    
                }

              
             }
             
             return RedirectToAction("Index");
        }


        public PartialViewResult Group(int groupID)
        {

            ViewBag.view = "group";
            ViewBag.id = groupID;
            using (var ctx = new ApplicationDbContext())
            {

                return PartialView("_Group", new GroupViewModel(groupID));

            }
        }
        public PartialViewResult AddUserToGroup() 
        { 
            return PartialView("_AddUser");
        }

        public ActionResult FileUpload(int groupID)
        {
            using (var ctx = new ApplicationDbContext())
            {
                var file = Request.Files["Filedata"];

                string savePath = Server.MapPath(@"~\Content\" + file.FileName);
                file.SaveAs(savePath);
                var thumbnailPath = "";
                if (MimeMapping.GetMimeMapping(file.FileName).Contains("image/"))
                {
                    var image = new Bitmap(savePath);
                    var thumbnail = image.GetThumbnailImage(100, 100, null, IntPtr.Zero);
                    thumbnailPath = Server.MapPath(@"~\Content\" 
                        + Path.GetFileNameWithoutExtension(file.FileName) 
                        + "_thumbnail" + Path.GetExtension(file.FileName));
                    thumbnail.Save(thumbnailPath);
                    
                }
                FileModel fm = new FileModel()
                    {
                        path = savePath,
                        groupId = groupID,
                        uploadDate = DateTime.Now,
                        FileType = MimeMapping.GetMimeMapping(file.FileName),
                        thumbnail = thumbnailPath
                    };
                ctx.file.Add(fm);
                ctx.SaveChanges();
                return Content(Url.Content(@"~\Content\" + file.FileName));
            }
        }

        public ActionResult Management(int groupID, IEnumerable<ApplicationUser> users){
            using(var ctx = new ApplicationDbContext()){
                var group = ctx.Groups.Where(p=>p.groupID==groupID).FirstOrDefault();
                var creator = ctx.Users.Where(p => p.UserName == group.creator).FirstOrDefault();
                var usersInGroup = ctx.userGroups.Where(p=> p.groupID==groupID).Select(p=>p.user).ToList();
                var usergroup = new UserGroup
                {
                    user = new ApplicationUser(),
                    group = group
                };
                foreach (var user in usersInGroup)
                {

                    usergroup = ctx.userGroups.Where(p => p.UserID == user.Id).Where(p => p.groupID == group.groupID).FirstOrDefault();
                    
                     ctx.userGroups.Remove(usergroup);
                }

                ctx.SaveChanges();
                addUserToGroup(creator, group, ctx);
                foreach (var user in users)
                {
                     var  sth = ctx.Users.FirstOrDefault(p=> p.UserName.Equals(user.UserName));
                     if (sth != null)
                     {
                         addUserToGroup(sth, group, ctx);
                     }
                }
                
                try
                {
                    // Your code...
                    // Could also be before try if you know the exception occurs in SaveChanges

                    ctx.SaveChanges();
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var eve in e.EntityValidationErrors)
                    {
                        Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                            eve.Entry.Entity.GetType().Name, eve.Entry.State);
                        foreach (var ve in eve.ValidationErrors)
                        {
                            Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                                ve.PropertyName, ve.ErrorMessage);
                        }
                    }

                }


            }

            return RedirectToAction("Index");
        }
        

      

        [HttpPost]
        public void Upload(int groupID)
        {
            
            if (Request.Files.Count > 0)
            {
                using (var ctx = new ApplicationDbContext())
                {
                    List<FileJSON> filesDTO = new List<FileJSON>();
                    var files = Request.Files;

                    foreach (string key in files)
                    {

                        var file = files[key];
                        if (MimeMapping.GetMimeMapping(file.FileName).Contains("image/") || MimeMapping.GetMimeMapping(file.FileName).Contains("audio/"))
                        {
                            string fileName = file.FileName;
                            // rename file to upload date time
                            var now = DateTime.Now;
                            string fileNameDateTime = now.Day.ToString()
                                + now.Month.ToString() + now.Year.ToString()
                                + now.Hour.ToString() + now.Minute.ToString()
                                + now.Second.ToString() + Path.GetExtension(file.FileName);
                            fileName = Server.MapPath("~/uploads/" + fileNameDateTime);
                            file.SaveAs(fileName);

                            var thumbnailPath = "";
                            var thumbnailPathStr = "";
                            if (MimeMapping.GetMimeMapping(file.FileName).Contains("image/"))
                            {
                                var image = new Bitmap(fileName);
                                var thumbnail = image.GetThumbnailImage(100, 100, null, IntPtr.Zero);
                                thumbnailPathStr = Path.GetFileNameWithoutExtension(fileNameDateTime)
                                    + "_thumbnail" + Path.GetExtension(fileName);
                                thumbnailPath = Server.MapPath("~/uploads/" + thumbnailPathStr);
                                thumbnail.Save(thumbnailPath);
                                image.Dispose();
                                thumbnail.Dispose();
                                Response.ContentType = MimeMapping.GetMimeMapping(file.FileName);
                            }

                            FileModel fm = new FileModel()
                            {

Kollaborator/Kollaborator.web/Views/Shared/_AddUser.cshtml
@model Kollaborator.web.Models.ApplicationUser

<div class="single-user-wrapper">
    <div id="editorRow">
        @using (Html.BeginCollectionItem("users"))
        {
            <div class="form-group">
                @Html.LabelFor(p => p.UserName, htmlAttributes: new { @class = "col-lg-4 control-label" })

                    @Html.EditorFor(p => p.UserName, new { htmlAttributes = new { @class = "col-lg-4 form-control input-md" } })
                    <a href="#" class="deleteRow">delete</a>
              
            </div>
        }
        

    </div>
</div>

Kollaborator/Kollaborator.web/Views/Shared/_Chat.cshtml
@model List<Kollaborator.web.Models.ChatModel>


<div class="row chat-window col-xs-5 col-md-3" id="chat_window" style="margin-left:10px;">
    <div class="col-xs-12 col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading top-bar">
                <div class="col-md-8 col-xs-8">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-comment"></span> @ViewBag.Group - Kollaborator</h3>
                </div>
                <div class="col-md-4 col-xs-4" style="text-align: right;">
                    <a href="#"><span id="minim_chat_window" class="glyphicon glyphicon-minus icon_minim"></span></a>

                </div>
            </div>
            <div id ="chatPanel" class="panel-body msg_container_base">
                <a href="#" id="btn-update" class="btn btn-xs btn-default"><span class="glyphicon glyphicon-repeat"></span> Load 25 more messages</a>
                @foreach (var message in Model)
                {
                    Html.RenderPartial("_ChatRow", message);
                    
                }
            </div>
            <div class="panel-footer">
                @{Html.RenderPartial("_ChatControlles", new Kollaborator.web.Models.ChatModel() { groupID = ViewBag.ID });}
                
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    
 
</script>

Kollaborator/Kollaborator.web/Views/Shared/_ChatControlles.cshtml
@model Kollaborator.web.Models.ChatModel



    
    <div id="chatInput" class="input-group">
    @Html.HiddenFor(m => m.groupID)
    <input id="btn-input" type="text" class="form-control input-sm chat_input" placeholder="Write your message here..." name="@Html.NameFor(m=>m.message)" />
    <span class="input-group-btn">
        <button class="btn btn-primary btn-sm" id="btn-chat" name="sendmessage">Send</button>
    </span>
</div>

<script src='~/signalr/hubs'></script>
<script type="text/javascript">

    
    $(document).ready(function() {
        var connection = $.connection.chatHub;

        var chat = $.connection.chatHub;

        $('#btn-update').click(function (){
            var updateData ={};
            updateData.groupId = @Model.groupID;
            updateData.oldestMessage = $(".msg_container:first").attr('id');

            $.ajax({
                url: '@Url.Action("LoadMoreMessages")',
                contentType: 'application/json; charset=utf-8',
                data: updateData,
                dataType: 'json',
                success: function (data) {
                    for(i = 0; i < data.length; i++){
                        $("#chatPanel").prepend(generateHtmlForMessage(data[i]));

                        
                    }
                    updateData.oldestMessage = $(".msg_container:first").attr('id');
                }
            });
        })
       
        function generateHtmlForMessage(msg){
            var sender = String(msg.sender);
            var currentuser = document.getElementById("currenuser").value;
            var encodedMsg="";
            if(sender==currentuser){
                encodedMsg= '<div class="row msg_container base_sent" id='+msg.messageID+' >    <div class="col-md-10 col-xs-10">';
                encodedMsg +=  '<div class="messages msg_sent"><p>'+msg.message+'</p>';
                encodedMsg += '<time datetime="@DateTime.Now">'+msg.sender+' - '+'timestamp</time></div></div><div class="col-md-2 col-xs-2 avatar"><img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle img-responsive" /></div></div>';
            } else{
                var firstLetterofName = sender.charAt(0);
                var imgSrc = "http://placehold.it/50/55C1E7/fff&text=" + firstLetterofName;
                encodedMsg+='<div class="row msg_container base_receive" id='+msg.messageID+'><div class="col-md-2 col-xs-2 avatar"><img src='+imgSrc+' class=" img-responsive img-circle" /></div><div class="messages msg_receive">';
                encodedMsg += '<p>'+msg.message+'</p><time datetime="2009-11-13T20:00">'+sender+' - '+'timestamp</time></div></div>';

            }
            // Add the message to the page.

            return encodedMsg;
        }
        $.connection.hub.logging = true;
        $("#chatPanel").scrollTop(1000000);
        connection.client.broadcastMessage = function (name, message) {
            // Html encode display name and message.
            var msg =JSON.parse(message);



            // Add the message to the page.

            $('#chatPanel').append(generateHtmlForMessage(msg));
        };


        $.connection.hub.start().done(function () {
            chat.invoke('subscribe', @Model.groupID);
            $('#btn-chat').click(function () {


                // Call the Send method on the hub.
                if($("#btn-input").val()!=""){

                    chat.server.send(@Model.groupID,$("#btn-input").val()) ;

                    // Clear text box and reset focus for next comment.
                    $("#btn-input").val('').focus();
                }
            });


        });});

    function convert(str)
    {
        str = str.replace("&amp;",/&/g);
        str = str.replace("&gt;",/>/g);
        str = str.replace("&lt;",/</g);
        str = str.replace("&quot;",/"/g);
        str = str.replace("&#039;",/'/g);
        return str;
    }














</script>

Kollaborator/Kollaborator.web/Views/Shared/_Create.cshtml
@model Kollaborator.web.Models.GroupModel


<h2>Create Group</h2>

<div id="container">
    @using (Html.BeginForm("Create", "Group"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <h5>Make your own music group</h5>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">

                @Html.LabelFor(model => model.groupName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.groupName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.groupName, "", new { @class = "text-danger" })
                </div>
                <div class="control-label col-md-2">
                    <a class="insert-new-user" href="javascript:insertNewUser()">Add a user</a>

                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>

            </div>

        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    $("a.deleteRow").live("click", function () {
        $(this).parents("div.single-user-wrapper:first").remove();
        return false;
    });
    function insertNewUser() {
        $.ajax({
            url: '@Url.Action("AddUserToGroup")',
            success: function (data) {
                if ($("div.single-user-wrapper:last").length > 0) {
                    $(data).insertAfter("div.single-user-wrapper:last");
                } else {
                    $(data).insertAfter("a.insert-new-user");
                }
            }
        });
    } </script>

Kollaborator/Kollaborator.web/Views/Shared/_ExistingUser.cshtml
@model Kollaborator.web.Models.ApplicationUser

<div class="single-user-wrapper">
    <div id="editorRow">
        <a href="javascript:void(0)" onclick="removeItem(this);">Remove this item</a>
        @using (Html.BeginCollectionItem("users"))
        {
            <div class="form-group">
                @Html.LabelFor(p => p.UserName)
                @Html.HiddenFor(p => p.Id)
                @Html.EditorFor(p => p.UserName, new { htmlAttributes = new { @Value = Model.UserName}, })



            </div>
        }


    </div>
</div>

Kollaborator/Kollaborator.web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" type="image/png" href="/note.png" />
   @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.signalR-2.2.0.js"> </script>
            @Scripts.Render("~/bundles/bootstrap")
            @Styles.Render("~/Content/css")
            @Scripts.Render("~/bundles/modernizr")
</head>
<body>
   
    <div class="page">
        @RenderBody()
    </div>
    

    
    @if (ViewBag.view == "group") { 
    <script type="text/javascript">
    $(function () {
        $('#file_upload').uploadify({
            'swf': "@Url.Content("~/Scripts/uploadify.swf")",
            'cancelImg': "~/Scripts/uploadify-cancel.png",
            'uploader': '@Url.Action("FileUpload", "Group", new { groupID = Model.Item1.groupID })',
            'onUploadSuccess': function (file, data, response) {
                $("#uploaded").append("<img src='" + data + "' alt='Uploaded Image' />");
            }
        });
    });

        
    </script>
    }
    <script type="text/javascript">
        
        function removeItem(link) {
            $(link).closest("div.single-user-wrapper").remove();
        }


        
        
    </script>
    @RenderSection("scripts", required: false)

    </body>
    </html>

Kollaborator/Kollaborator.web/Views/Shared/_Management.cshtml
@model List<Kollaborator.web.Models.UserGroup>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserGroup</h4>
        <hr />
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Kollaborator/Kollaborator.web/Views/Shared/_Register.cshtml
@model Kollaborator.web.Models.RegisterViewModel

<div id="signupbox" style="display:none; margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
        <div class="panel-heading">
            <div class="panel-title">Sign Up</div>
            <div style="float:right; font-size: 85%; position: relative; top:-10px"><a id="signinlink" href="#" onclick="$('#signupbox').hide(); $('#loginbox').show()">Sign In</a></div>
        </div>
        <div class="login-panel-body">
            @using (Html.BeginForm("Register", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div id="signupalert" style="display:none" class="alert alert-danger">
                    <p>Error:</p>
                    <span></span>
                </div>



                <div class="form-group">
                    <label for="email" class="col-md-3 control-label">Email</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="@Html.NameFor(m=>m.Email)" placeholder="Email Address">
                    </div>
                </div>

                <div class="form-group">
                    <label for="email" class="col-md-3 control-label">Username</label>
                    <div class="col-md-9">
                        <input type="text" class="form-control" name="@Html.NameFor(m=>m.Username)" placeholder="Username">
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-md-3 control-label">Password</label>
                    <div class="col-md-9">
                        <input type="password" class="form-control" name="@Html.NameFor(m=>m.Password)" placeholder="Password">
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-md-3 control-label">Confirm password</label>
                    <div class="col-md-9">
                        <input type="password" class="form-control" name="@Html.NameFor(m => m.ConfirmPassword)" placeholder="Password">
                       
                    </div>
                </div>

                <div class="form-group">
                    <!-- Button -->
                    <div class="col-md-offset-3 col-md-9">
                        <button id="singlebutton" name="singlebutton" class="btn btn-success">Sign Up</button>
                        
                    </div>
                </div>





            }
        </div>
    </div>




</div>